name: Build Custom PHP Micro.sfx

on:
  workflow_dispatch: # 允许你在 GitHub 页面手动点击运行

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout static-php-cli
        uses: actions/checkout@v4
        with:
          repository: 'i900xz/static-php-cli'
          ref: 'main' # 使用主分支

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3' # 用于运行构建工具的 PHP 版本
          extensions: mbstring, curl

      - name: Install Composer Dependencies
        run: composer install --no-dev --classmap-authoritative

      - name: Fetch Sources
        run: |
          # 注入你需要编译的扩展，这里包含了你列出的所有 27 个扩展
          ./bin/spc download --with-php=8.3 \
          bcmath,calendar,curl,dom,filter,hash,iconv,json,libxml,mysqlnd,pcre,pdo,phar,random,readline,session,simplexml,spl,standard,tokenizer,xml,xmlreader,xmlwriter,zlib

      - name: Build micro.sfx
        run: |
          # 提示：Core, date, Reflection, ctype 通常是 PHP 内置无法或无需关闭的，直接编译即可
          # 如果提示缺少依赖库，spc 会自动下载 openssl, libxml, readline, zlib, curl 等底层库
          ./bin/spc build \
          bcmath,calendar,curl,dom,filter,hash,iconv,json,libxml,mysqlnd,pcre,pdo,phar,random,readline,session,simplexml,spl,standard,tokenizer,xml,xmlreader,xmlwriter,zlib \
          --build-micro

      - name: Upload micro.sfx Artifact
        uses: actions/artifacts@v4
        with:
          name: php-micro-sfx
          path: buildroot/bin/micro.sfx
