name: Build Custom PHP Micro.sfx

on:
  workflow_dispatch: # 允许手动点击运行

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout static-php-cli
        uses: actions/checkout@v4
        with:
          repository: 'i900xz/static-php-cli'
          ref: 'main'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, curl

      - name: Install Composer Dependencies
        run: composer install --no-dev --classmap-authoritative

      - name: Run SPC Doctor (Install Build Dependencies)
        run: ./bin/spc doctor --auto-fix

      # 修改了这里：使用 -e 参数把你要编译的扩展传给它，让它精确计算并下载对应的源码
      - name: Fetch Sources
        run: |
          ./bin/spc download --with-php=8.4 -e \
          "bcmath,calendar,curl,dom,filter,hash,iconv,json,libxml,mysqlnd,pcre,pdo,phar,random,readline,session,simplexml,spl,standard,tokenizer,xml,xmlreader,xmlwriter,zlib"

      - name: Build micro.sfx
        run: |
          ./bin/spc build \
          bcmath,calendar,curl,dom,filter,hash,iconv,json,libxml,mysqlnd,pcre,pdo,phar,random,readline,session,simplexml,spl,standard,tokenizer,xml,xmlreader,xmlwriter,zlib \
          --build-micro

      - name: Upload micro.sfx Artifact
        uses: actions/upload-artifact@v4
        with:
          name: php-micro-sfx
          path: buildroot/bin/micro.sfx
